name: "Update Notion"
description: "Update Notion task status from Github PR actions"
author: "Nathan Kwan"
inputs:
  notion-status-prop:
    description: "Notion status property name"
    required: false
    default: "Status"
  notion-github-url-prop:
    description: "Notion Github URL property name"
    required: false
    default: "Github URL"
  draft:
    description: "Status to set when pull request is 'draft'"
    required: false
  merged:
    description: "Status to set when pull request is 'merged'"
    required: false
  assigned:
    description: "Status to set when pull request is 'assigned'"
    required: false
  unassigned:
    description: "Status to set when pull request is 'unassigned'"
    required: false
  labeled:
    description: "Status to set when pull request is 'labeled'"
    required: false
  unlabeled:
    description: "Status to set when pull request is 'unlabeled'"
    required: false
  opened:
    description: "Status to set when pull request is 'opened'"
    required: false
  edited:
    description: "Status to set when pull request is 'edited'"
    required: false
  closed:
    description: "Status to set when pull request is 'closed'"
    required: false
  reopened:
    description: "Status to set when pull request is 'reopened'"
    required: false
  synchronize:
    description: "Status to set when pull request is 'synchronize'"
    required: false
  ready_for_review:
    description: "Status to set when pull request is 'ready_for_review'"
    required: false
  locked:
    description: "Status to set when pull request is 'locked'"
    required: false
  unlocked:
    description: "Status to set when pull request is 'unlocked'"
    required: false
  review_requested:
    description: "Status to set when pull request is 'review_requested'"
    required: false
  api_key:
    description: "Notion API key"
    required: true
runs:
  using: "node16"
  main: "./index.js"
